POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer 1234

{
    "title": "Fourth blog post",
    "author": "Mikael",
    "url": "/third",
    "likes": "2",
    "userId": "62fbac956cd5c2b994e867af"
}