POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGcI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIxMjMiLCJpZCI6IjYyZmJhYzk1NmNkNWMyYjk5NGU4NjdhZiIsImlhdCI6MTY2MDkxNDIwOH0.FROYYturktl-_40Blq3-MdkSeNcqh_Cmh61ImNKfPcE

{
    "title": "Fourth blog post",
    "author": "Mikael",
    "url": "/third",
    "likes": "2",
    "userId": "62fbac956cd5c2b994e867af"
}